sonar.projectKey=devops-helloworld
sonar.projectName=DevOps HelloWorld
sonar.sources=.
sonar.language=html
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqa_883a1375356c9f65648873b558a53ceca56196d5
